### ISSUE TITLE
PDF Invoice

### ISSUE THREAD

**Issue by PubliAlex** [oc-shopaholic/oc-orders-shopaholic-plugin#106]
Hello,

PDF Invoice generation is a must for every ecommerce plateform. But I didn't find how to do this with shopaholic. Did I miss something ?

Regards,

**Comment by lautsevich** [comment]
Hi @PubliAlex!

There's no built-in functionality for generating invoices. We recommend you to use the [DynamicPDF](https://octobercms.com/plugin/renatio-dynamicpdf) plugin for October CMS. Please, take a look at it!

**Comment by lautsevich** [comment]
Duplicates #112.
