### ISSUE TITLE
Search for Shopaholic - search_synonym

### ISSUE THREAD

**Issue by davidprovaznikj** [oc-shopaholic/oc-orders-shopaholic-plugin#107]
Hi,
is there some possibility to show search_synonym on product page?
Thank you.

**Comment by kharanenka** [comment]
Hi! You should extend Product model and add search_synonym to cache
For example:
```
Product::extend(function ($obProduct) {
        /** @var Product $obProduct */
        $obProduct->addCachedField(['search_synonym']);
});
```

**Comment by davidprovaznikj** [comment]
Its working, Thank you!

Dne čt 11. 6. 2020 16:24 uživatel Andrey Kharanenka <
notifications@github.com> napsal:
