### ISSUE TITLE
Missing avaible properties in filter

### ISSUE THREAD

**Issue by zaqsk** [oc-shopaholic/oc-orders-shopaholic-plugin#114]
Hello 

When I imported products Im missing avaible properties (Výška and Šírka) in filter - only the first one is visible.
Motiv properties are working good, but the Výška and Šírka properties shows only first option:
<img width="1306" alt="Screenshot 2020-07-20 at 12 22 07" src="https://user-images.githubusercontent.com/25805698/87927600-be45e680-ca83-11ea-82b6-908dd9a69638.png">

Products have the properties set:
<img width="1316" alt="Screenshot 2020-07-20 at 12 24 10" src="https://user-images.githubusercontent.com/25805698/87927716-f0574880-ca83-11ea-9ee0-9397cf4d6b01.png">

Im using lovata sneakers theme, can you please fix it? Or am I doing something wrong, I've set everything exaclty like the Motiv property but nothing works. 

Thanks.

**Comment by kharanenka** [comment]
Hi! Do you have correct values for these properties on the product page?

**Comment by zaqsk** [comment]
Hi I didnt do anything special, but its working now :)
