### ISSUE TITLE
Sending email to customer after change order status

### ISSUE THREAD

**Issue by m-wysocki** [oc-shopaholic/oc-orders-shopaholic-plugin#121]
Hi,

how can I send email to customer after change order status?

**Comment by kharanenka** [comment]
Hi! You can add event on Order model (for example [afterSave](https://octobercms.com/docs/database/model#events)) and check changes of status_id field.
For example:
```php
if ($obOrder->status_id != $obOrder->getOriginal('status_id')) {
    //do something
}
```
