### ISSUE TITLE
! IMPORTANT  -  All orders prices rendered rounded 

### ISSUE THREAD

**Issue by turanzamanli** [oc-shopaholic/oc-orders-shopaholic-plugin#134]
I have installed oc-orders plugin. 
My  all orders prices return rounded, also product's price,

<img width="1287" alt="Screen Shot 2021-01-28 at 16 50 06" src="https://user-images.githubusercontent.com/25426605/106141406-7833b300-6189-11eb-839b-078f7d55dadb.png">

**Comment by kharanenka** [comment]
What prise settings do you have? Go to /backend/system/settings/update/lovata/toolbox/config  -> Price format tab

**Comment by turanzamanli** [comment]
Thank you, I think it has to set to 2 decimal by default.
