### ISSUE TITLE
Properties Plugin - too many property tabs

### ISSUE THREAD

**Issue by quildcrest** [oc-shopaholic/oc-orders-shopaholic-plugin#148]
I just installed the properties plugin for Shopaholic. The problem is, too many property tabs were created on the product edit page, some of them couldn't be seen at all. There sure is one tab named properties but there are only several properties list in that tab.
Did I do something wrong? How to fix it?

Thanks.

![Screenshot_2021-03-17 Edit product OctoberCMS](https://user-images.githubusercontent.com/72320575/111413219-37014f00-86b4-11eb-93ab-fa14ea12a14a.png)

**Comment by mennax** [comment]
Hi, @quildcrest 

I think you should leave empty the "Tab name" field

![Screen Shot 2021-03-21 at 11 17 28](https://user-images.githubusercontent.com/8210143/111901309-9acea380-8a37-11eb-88cf-b8e4051c545f.png)

**Comment by quildcrest** [comment]
That's right. Thank you very much.
