### ISSUE TITLE
Unable to install shopaholic on October 1.1.5

### ISSUE THREAD

**Issue by Roby-Wan-Kenobi** [oc-shopaholic/oc-orders-shopaholic-plugin#154]
After the installation of Lovata/Toolbox if I type "php artisan plugin:install lovata.shopaholic"  I've got this error:
'Kharanenka\Scope\ActiveField' not found  
It doesn't find lots of dependencies. Must I use a specific version of shopaholic?

**Comment by kharanenka** [comment]
Hi! Please install packages from composer file in Lovata.Toolbox plugin. You can run ```composer install``` in plugin folder or add packages in main composer file

**Comment by Roby-Wan-Kenobi** [comment]
Thanks a lot now it works
