### ISSUE TITLE
Support for multiple vendors

### ISSUE THREAD

**Issue by LarryBarker** [oc-shopaholic/oc-orders-shopaholic-plugin#160]
Hello, apologies if this isn't the proper format for this question.

Is it possible to support multiple vendors? We want to create a "marketplace" where multiple vendors can sell the same type of product.

**Comment by lautsevich** [comment]
@LarryBarker, pls, follow this [link](https://github.com/oc-shopaholic/oc-shopaholic-plugin/issues/176) to get more information about this feature.
