### ISSUE TITLE
In Currency.php line 42:    Trait 'Kharanenka\Scope\ActiveField' not found

### ISSUE THREAD

**Issue by kondratyukov** [oc-shopaholic/oc-orders-shopaholic-plugin#162]
installation error - In Currency.php line 42:    Trait 'Kharanenka\Scope\ActiveField' not found. Please help

**Comment by igor-tv** [comment]
As a quick fix, try running `composer i` in the plugins/lovata/toolbox folder.

**Comment by kondratyukov** [comment]
I'm sorry, I'm a beginner programmer. In the directory ../plugins/lovata/toolbox, enter the command in the console - composer i. But after that it still gives the error "Trait 'Kharanenka \ Scope \ ActiveField' not found"(

**Comment by kondratyukov** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/57134969/128538849-f2331aea-3cf0-407e-b43a-100a8c39d9f5.png)

**Comment by igor-tv** [comment]
The error says that you have openssl disabled. Install this extension. Or install Laragon instead of Open Server, there will be no such problems.

**Comment by igor-tv** [comment]
The error says that you have openssl disabled. Install this extension. Or install Laragon instead of Open Server, there will be no such problems.

**Comment by kondratyukov** [comment]
Laragon helped! Thank's
