### ISSUE TITLE
Cannot find created before payment method (paypal)

### ISSUE THREAD

**Issue by gvanto** [oc-shopaholic/oc-orders-shopaholic-plugin#165]
I want to purchase Paypal plugin and looking at docs: https://octobercms.com/plugin/lovata-paypalshopaholic > Documentation

I can't seem to see where the 'created before payment method' is referred to here?:
![image](https://user-images.githubusercontent.com/8372918/130743228-83a75eee-4137-429e-a7c2-7a26b0179889.png)

Is there an example of setting up a Paypal payment in the docs somewhere? 
(no Paypal docs here: https://shopaholic.one/docs#/plugins/home)

Thanks,
gvanto

**Comment by gvanto** [comment]
Also, is there a way to create a Paypal subscription (instead of just a once-off order) ?

**Comment by gvanto** [comment]
This is the payment method created - where do I put the (paypal) token?

![image](https://user-images.githubusercontent.com/8372918/132117017-9ef611d9-0224-4503-8673-b487b1edc95b.png)

**Comment by lautsevich** [comment]
Closed in favor [oc-shopaholic-plugin/issues/388](https://github.com/oc-shopaholic/oc-shopaholic-plugin/issues/388).
