### ISSUE TITLE
Add product to cart

### ISSUE THREAD

**Issue by ricardsbe** [oc-shopaholic/oc-orders-shopaholic-plugin#171]
Hello!
I am new at programming, and i want to know why my add to cart ajax function is not working..
AJAX :
$('body').on('click', '.add-grozs', function (e) {
    var data = {
        'cart': [
            {'offer_id': 2, 'quantity': 4}
        ]
    };
    
$('body').on('click', '.add-grozs', function (e) {
    var data = {
        'cart': [
            {'offer_id': 2, 'quantity': 4}
        ]
    };
    
    //Send ajax request and update cart items
    $.request('Cart::onAdd', {
        'data': data,
        'update': {'grozs': '.cart'}
    });
});
Html button:

            <button class="add-grozs">Add to cart</button>
Thanks!

**Comment by kharanenka** [comment]
Hi! What response form Cart component do you have?

**Comment by ricardsbe** [comment]
Thanks! I solved everything. Now i have another problem , i have addeed account page, everything is working fine, in account page name is showing of user, but how i can add a order field to show which orders client have made

**Comment by kharanenka** [comment]
Hi! You can find examples [here](https://shopaholic.one/docs#/modules/order/examples/examples?id=example-3-user-order-list)

**Comment by ricardsbe** [comment]
Hi! It is showing fallowing error, when i am trying to add order page
Type error: Too few arguments to function Lovata\OrdersShopaholic\Classes\Event\User\UserModelHandler::Lovata\OrdersShopaholic\Classes\Event\User\{closure}(), 0 passed and exactly 1 expected

**Comment by ricardsbe** [comment]
Could you please help me?

**Comment by kharanenka** [comment]
Hi! Please send us full error log. Now it is difficult for me to understand what the error is. What user plugin are you using in your project?

**Comment by ricardsbe** [comment]
I an using buddies. 
Full eror screeen shot 
https://prnt.sc/26cf1qa

**Comment by kharanenka** [comment]
Try to change 158 line in plugins/lovata/ordersshopaholic/classes/event/user/UserModelHandler.php file from:
```php
$obUserItem->addDynamicMethod('getOrderAttribute', function ($obUserItem) {
```
to
```php
$obUserItem->addDynamicMethod('getOrderAttribute', function () use ($obUserItem) {
```

**Comment by ricardsbe** [comment]
Thanks! You helped me a lot! Now orders work!

**Comment by ricardsbe** [comment]
And one more question how to do auto fill when making order if client is logged in

**Comment by kharanenka** [comment]
It is default logic in Orders plugin. MakeOrder component gets loggined user and attaches it to new orders

**Comment by ricardsbe** [comment]
Ok, thanks!
