### ISSUE TITLE
Shopaholic   Components not showing any results

### ISSUE THREAD

**Issue by adalkhan001** [oc-shopaholic/oc-orders-shopaholic-plugin#181]
In admin all the setting is available but after adding Shopaholic components not showing any results.
![Screenshot_4](https://user-images.githubusercontent.com/95270715/208603675-1f298c8e-72ff-4b3f-86bc-0f90632a6136.png)

**Comment by igor-tv** [comment]
Hi, @adalkhan001 

Components don't have templates. Components allow you to get objects of ElementItem, ElementCollection classes. Read more in the [documentation](https://shopaholic.one/docs#/architecture/architecture?id=components).
