### ISSUE TITLE
Properties methods access issue

### ISSUE THREAD

**Issue by euge001** [oc-shopaholic/oc-orders-shopaholic-plugin#189]
Hi!

When I use: 

        {% set obPropertyList = obProduct.property %}
        <ul>
            {% for obProperty in obPropertyList %}
                <li>
                      {{ obProperty.name }}: {{ obProperty.property_value.getValueString() }} {{ obProperty.measure.name }} 
                </li>
            {% endfor %}
        </ul>

I can successfully see all the properties in my product slider.

However this piece of code:

                  {% set obPropertyList = obProduct.property %}
                  {% set obGroupList = obPropertyList.getGroupList() %}
                  {% set obMainGroup = obGroupList.getByCode('main') %}
    
                  {% set obPropertyList = obPropertyList.group(obMainGroup.id) %}
    
            <ul>
                {% for obProperty in obPropertyList %}
                    <li>
                          {{ obProperty.name }}: {{ obProperty.property_value.getValueString() }} {{ obProperty.measure.name }}
                          {{ obMainGroup.name }}
                   </li>
                {% endfor %}
            </ul>

returns nothing, even I have all the Properties and Property Sets in place. Main ('main') - is the code of existing set with products and properties inside.

**Comment by kharanenka** [comment]
Hi!
*  You should create property group with code "main" (/backend/lovata/propertiesshopaholic/groups). 
* You should select groups in properties, when you configure property set and related properties (/backend/lovata/propertiesshopaholic/propertysets/update/1)

**Comment by euge001** [comment]
thank you for your responce.
Both of steps has been done. I did follow your youtube tutorial and did check several times I follow it properly.
This is how my set is looks like: 
![image](https://github.com/oc-shopaholic/oc-orders-shopaholic-plugin/assets/12379144/80b6419f-f496-4e9f-8afa-ad1f5c34b266)

**Comment by kharanenka** [comment]
But you should see checkbox list in "Property grous" field. Why do you see "input text" field?

![example](https://github.com/oc-shopaholic/oc-orders-shopaholic-plugin/assets/18258760/8aefe455-19c9-4147-a516-5fee856f0fd3)

**Comment by euge001** [comment]
is there any chance to get support for this issue?

**Comment by kharanenka** [comment]
Have you solved your issue?

**Comment by euge001** [comment]
Hi!
Yes, thank you.
