### ISSUE TITLE
Overriding toolbars

### ISSUE THREAD

**Issue by mintyPT** [oc-shopaholic/oc-orders-shopaholic-plugin#61]
Hey guys,

Thanks for the good work. I'm currently working on a new project while using your plugin and got into a problem.

I need to override the toolbar for the order's list. Is it possible? I didn't find a way to do so.

**Comment by kharanenka** [comment]
Hi! It is available. 
Since there is no standard way to do this, then you have to make workarounds.
You can extend Orders controller and change path to list config in $listConfig.
In your config file you are modifying to specify path to your toolbar file.

Orders::extend(function($obController) {
    $obController->listConfig = 'my/custom/path';
});

**Comment by mintyPT** [comment]
That part I understand and it makes perfect sense.

What I don't understand is where to put that on my project since I'm trying to override a piece of a plugin.

**Comment by mintyPT** [comment]
Yeah. I think I'm being stupid.

> **In the long run we get no more than we have been willing to risk giving.**
> Sheldon Kopp

**Comment by kharanenka** [comment]
You need to create your custom plugin. 
You can reed docs:
https://octobercms.com/docs/plugin/extending
https://octobercms.com/docs/services/behaviors

This should help you.

**Comment by mintyPT** [comment]
I really was being stupid. Found how to do it after 2 minutes of posting my last message.

Thanks

**Comment by mintyPT** [comment]
The more I advance the more I learn but got into another issue. How do I override the create/update templates for the orders? If I try the same method than before, it still implicitly takes the files from the plugin.


> **Imagination is the highest kite one can fly.**
> Lauren Bacall

**Comment by kharanenka** [comment]
It may be easier for you to create your controller and extend it from Orders controller.

**Comment by mintyPT** [comment]
But since your plugin will still be active, which controller will it take?

> **Life is the flower for which love is the honey.**
> Victor Hugo

**Comment by kharanenka** [comment]
Yes you are right, not everything will work correctly. 
It is necessary to use main controller, but try to somehow change everything in it through extensions.
I have no idea how to change create/update templates.
