### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by FlusherDock1** [oc-shopaholic/oc-orders-shopaholic-plugin#76]
Found a small bug, that can't let the user open the website again.

**Steps to reproduce:**
1. Clear Shopaholic + Shopaholic Orders install
2. Add simple product with one offer
3. Go to frontend (Free bootstrap template for example)
4. Place product to cart
5. Open cart and change quantity of products to 1000 or more.
6. Change it several times, 1000 > 10000 > 20000 until you get error from AJAX.
7. Now the user blocked from the website, and can't enter it until his session is cleared.

![Снимок экрана 2019-09-06 в 11 53 19](https://user-images.githubusercontent.com/20070837/64414925-f11a0280-d09c-11e9-8ab3-38acd06358a4.png)

The user should not be blocked from website after one error.

I understand that these numbers is unreal in typical e-commerce, but let's think about maybe a B2B shop with big packages.

**Comment by lautsevich** [comment]
Thx, we'll check it. Feel free to send a PR with a fix if you have one.

**Comment by kharanenka** [comment]
You need to increase **memory_limit** param in your php.ini
It is not plugin error.
