### ISSUE TITLE
already install Lovata Properties BUT get nothing

### ISSUE THREAD

**Issue by thangtran2019** [oc-shopaholic/oc-orders-shopaholic-plugin#80]
![image](https://user-images.githubusercontent.com/58036353/69340645-8723f900-0c9a-11ea-89c9-95a75144eb34.png)

![image](https://user-images.githubusercontent.com/58036353/69340585-707da200-0c9a-11ea-9341-85abab9d13d4.png)

Please help me to fix it.

Thanks

**Comment by kharanenka** [comment]
Hi. You can configure properties and property sets in "Settings" -> "Properties" section

**Comment by thangtran2019** [comment]
thanks for your support. i find it
