### ISSUE TITLE
Question: How to get fields info added in Products

### ISSUE THREAD

**Issue by thangtran2019** [oc-shopaholic/oc-orders-shopaholic-plugin#81]
![image](https://user-images.githubusercontent.com/58036353/69482199-c85b0b00-0e4a-11ea-8bb3-e9fe007dea48.png)

As showed, how can i get Products info for some fields I added the Products models.

Thanks

**Comment by kharanenka** [comment]
Hi! You need to extend main plugin. You can find full information about extending in new [docs](http://shopaholic.one/docs#/modules/product/extending/extending)

**Comment by thangtran2019** [comment]
thanks for your support
