### ISSUE TITLE
Question: How to send Offer List in confirmation emails

### ISSUE THREAD

**Issue by AvanOsch** [oc-shopaholic/oc-orders-shopaholic-plugin#83]
How would I go about sending the Offer List (and/or other order info) along with confirmation emails?

**Comment by AvanOsch** [comment]
Digging through the code, I made some progress on this.
Apart from **order_number** and **site_url**, we can access **order**.

I only need some extra info added to this list (Product and Offer name, currency).

My code so far:
```
{% for obOffer in order.order_position %}
- {{ obOffer.quantity }}x <b>{{ obOffer.code }}</b> {{ obOffer.item_id }} ({{ obOffer.price }})<br/>
{% endfor %}
```

**Comment by kharanenka** [comment]
Hi! You need to change your template code:
```
{% for obOrderPosition in order.order_position %}
  {% set obOffer = obOrderPosition.item %}
- {{ obOrderPosition.quantity }}x <b>{{ obOffer.code }}</b> {{ obOffer.item_id }} {{ obOffer.name }} ({{ obOffer.price }} {{ order.currency.symbol }})
<br/>
{% endfor %}
```

**Comment by AvanOsch** [comment]
Perfect!
Thank you very much!

**Comment by AvanOsch** [comment]
Follow-up question about this;
Is it also possible to get the Product name from somewhere?
