### ISSUE TITLE
How use Filter for ProductList

### ISSUE THREAD

**Issue by batmar96** [oc-shopaholic/oc-orders-shopaholic-plugin#93]
how to filter a list of products using the filter for Shopogolick plugin?
{% set obProductList = obProductList.filterByProperty(input('property'), obCategory.product_filter_property) %} not working

**Comment by kharanenka** [comment]
Hi! What do you have in input('property')?

**Comment by batmar96** [comment]
> Hi! What do you have in input('property')?

get запрос /prodazha?property%5B2%5D%5B%5D=buksir&property%5B15%5D%5B%5D=rxvolga&set_filter=Y

**Comment by kharanenka** [comment]
Please send array you receive from ```input('property')```

**Comment by batmar96** [comment]
> Please send array you receive from `input('property')`

2: buksir
15: rxvolga

**Comment by kharanenka** [comment]
You should debug plugins/lovata/filtershopaholic/classes/event/ProductModelHandler.php file, line 206

**Comment by batmar96** [comment]
> You should debug
with such parameters /prodazha?property%5B2%5D=barzha&set_filter=Y

in ProductModelHandler.php print_r($arFilterList);=  Array ( [2] => barzha )

**Comment by batmar96** [comment]
> You should debug plugins/lovata/filtershopaholic/classes/event/ProductModelHandler.php file, line 206

the question is closed
